language: python
sudo: false

python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt

before_script:
  - echo "Checking for git version..."
  - git --version

script:
  - export PYTHONPATH=$PYTHONPATH:.
  - py.test --cov gitstats --cov-report term-missing --durations=10

after_success:
- coveralls
